//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBletchleyCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int Wins { get; set; }
        public int Guesses { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PlayerInfoTable PlayerInfoTable { get; set; }
    }
}
